export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // Inherit the top-level <html>/<body> from app/layout.tsx to avoid nesting
  return <>{children}</>
}
